// Copyright (C) 2020  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 20.1 (Build Build 720 11/11/2020)
// Created on Tue Apr 22 21:15:49 2025

LCDboard LCDboard_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.lcd_data(lcd_data_sig) ,	// inout [7:0] lcd_data_sig
	.lcd_rs(lcd_rs_sig) ,	// output  lcd_rs_sig
	.lcd_rw(lcd_rw_sig) ,	// output  lcd_rw_sig
	.lcd_e(lcd_e_sig) ,	// output  lcd_e_sig
	.lcd_reset(lcd_reset_sig) ,	// input  lcd_reset_sig
	.operation(operation_sig) ,	// input  operation_sig
	.A(A_sig) ,	// input [15:0] A_sig
	.B(B_sig) ,	// input [15:0] B_sig
	.R(R_sig) 	// input [15:0] R_sig
);

